version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: docker build
          command: docker build -t forked_qmk_build .
      - run:
          name: docker run
          command: docker run -e keymap=shimarin -e keyboard=helix --rm -v $('pwd'):/qmk:rw -t forked_qmk_build
      - store_artifacts:
          path: .build/helix_rev2_shimarin.hex
